### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by emahuni** [micromatch/picomatch#123]
The previous versions had a dependency on nodejs specific modules and am happy to see that that is no longer the case in the latest versions. However, just one little thing still lingers; `require('os')`, in the `index.js` file. A fix for this will mean that this will work well in the browser as well.

here is the offending code snippet from index.js
```js

const os = require('os');
const pico = require('./lib/picomatch');

const isWindows = os.platform() === 'win32';

```

**Comment by gwsbhqt** [comment]
I have the same problem and I want to use this library on my browser

**Comment by jonschlinkert** [comment]
Want to do a PR?

**Comment by gwsbhqt** [comment]
@jonschlinkert No problem, check PR https://github.com/micromatch/picomatch/pull/124.
@emahuni And thanks for your code.

**Comment by gwsbhqt** [comment]
@jonschlinkert Is there any progress?

**Comment by eichiflSICKAG** [comment]
@jonschlinkert we are really looking forward to this feature. 
Is there anything needs to be done?

**Comment by jonschlinkert** [comment]
Closing, since this should be fixed by v4
