### ISSUE TITLE
Wrong result for file with leading `.`

### ISSUE THREAD

**Issue by vvscode** [micromatch/picomatch#127]
```ts
require('picomatch')('src/microfrontends/**')('src/microfrontends/xxxx/.eslintrcjs') // false
require('picomatch')('src/microfrontends/**')('src/microfrontends/xxxx/x.eslintrcjs') // true
```

Discovered on version `2.3.1`, but it's still there for `3.0.1`

I even see tests for such cases https://github.com/micromatch/picomatch/blob/master/test/globstars.js#L83 but don't understand the idea behind those tests (looks like it's done on purpose)

**Comment by jonschlinkert** [comment]
Hi @vvscode, we follow bash and minimatch conventions and this is expected behavior. See the `dot` option in [the readme](https://github.com/micromatch/picomatch?tab=readme-ov-file#options).
