### ISSUE TITLE
Safari: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by Aysnine** [micromatch/picomatch#15]
https://github.com/micromatch/picomatch/blob/f364c5bc3412bf029a60540cfdd5c85dcbd6a2a9/lib/scan.js#L219-L223

Copy that function, paste to Safari like:
``` js
;(function removeBackslashes(str) {
  return str.replace(/(?:\[.*?(?<!\\)\]|\\(?=.))/g, match => {
    return match === '\\' ? '' : match;
  });
})('wow');
// => SyntaxError: Invalid regular expression: invalid group specifier name
```

Maybe relevant:
https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by jonschlinkert** [comment]
it's the negative lookbehind: `(?<!\\)`. I'll get a patch pushed up, thanks for creating the issue.

**Comment by jonschlinkert** [comment]
Please reopen if you still experience issues after pulling down the latest version. thanks!

**Comment by Aysnine** [comment]
Nice! It's work for me :)
Can you update the dependence of micromatch? thanks!

**Comment by jonschlinkert** [comment]
> Can you update the dependence of micromatch? thanks!

No need, semver takes care of this. You'll need to delete any `.lock` files and reinstall everything.
