### ISSUE TITLE
Const instead of let usage suggestion

### ISSUE THREAD

**Issue by DarkPark** [micromatch/picomatch#19]
https://github.com/micromatch/picomatch/blob/9eb9a71780035c5c3e2c1e67eafa3d967f2289b2/lib/scan.js#L59

in this line and some other

**Comment by jonschlinkert** [comment]
> Const instead of let usage suggestion

What is the reason? A little more information would be helpful. Thanks

**Comment by DarkPark** [comment]
there are a lot of articles about it, for example - https://medium.com/dailyjs/use-const-and-make-your-javascript-code-better-aac4f3786ca1

in short - `let` is used when you need to change the value later, but in this case `advance` is a normal permanent immutable function

in general in this project I see an inconsistent approach - some files partially use `const` correctly (for objects, functions and so on) but in some places it appear as `var` was just replaces with `let` without giving it a second thought
