### ISSUE TITLE
globstar option has no affect for patterns without prefix

### ISSUE THREAD

**Issue by mrmlnc** [micromatch/picomatch#20]
### Environment

* Windows 10 (1903)
* Node.js 12.3.1
* picomatch 2.0.7

### Actual behaviour

```js
const a = mm.isMatch('a/b/c', '**', { noglobstar: false });
const b = mm.isMatch('a/b/c', '**', { noglobstar: true });

console.log(a, b); // true true

const c = mm.isMatch('a/b/c', 'a/**', { noglobstar: false });
const d = mm.isMatch('a/b/c', 'a/**', { noglobstar: true });

console.log(c, d); // true false
```

RegExp's:

```js
a: /^(?:(?!\.)(?:(?:(?!(?:^|[\\\/])\.).)*?)[\\\/]?)$/
b: /^(?:(?!\.)(?:(?:(?!(?:^|[\\\/])\.).)*?)[\\\/]?)$/
c: /^(?:a(?:[\\\/](?!\.)(?:(?:(?!(?:^|[\\\/])\.).)*?)|$))$/
d: /^(?:a[\\\/](?!\.)[^\\\/]*?[\\\/]?)$/
```

### Expected behaviour

For case `b` and `d`, I expect `false` based on the `globstar` option description and [`bash shopt -s globstar`](https://www.linuxjournal.com/content/globstar-new-bash-globbing-option).

> Disable support for matching nested directories with globstars (`**`).

```
console.log(a, b); // true false
console.log(c, d); // true false
```

**Comment by mrmlnc** [comment]
Most likely this is related to `fastpaths` functionality.

**Comment by jonschlinkert** [comment]
> Most likely this is related to `fastpaths` functionality.

thanks for the debugging. Did you try disabling fastpaths to see if it works? I think I forgot about that rule when I added support for fastpaths. A fix should be pretty easy if that is indeed what's causing the issue.

**Comment by mrmlnc** [comment]
Yeap, works correctly with `fastpaths: false`:

```js
a: /^(?:(?:(?:(?!(?:^|[\\\/])\.).)*?))$/
b: /^(?:(?!\.)[^\\\/]*?[\\\/]?)$/
c: /^(?:a(?:[\\\/](?!\.)(?:(?:(?!(?:^|[\\\/])\.).)*?)|$))$/
d: /^(?:a[\\\/](?!\.)[^\\\/]*?[\\\/]?)$/
```

**Comment by jonschlinkert** [comment]
> Yeap, works correctly with `fastpaths: false`:

great, thanks for checking!

**Comment by mrmlnc** [comment]
Thanks :tada: Don't worry, it's not urgent :)
