### ISSUE TITLE
Brace expansion matches single item

### ISSUE THREAD

**Issue by mojavelinux** [micromatch/picomatch#49]
According to the braces library, braces expansion should not match a single item like `{foo}`. However, picomatch does interpret this expression.

braces:

```js
braces('{foo}')
//=> ['{foo}']
```

picomatch:

```js
picomatch.parse('{foo}').output
//=> '(foo)'
```

Compare that to when there are multiple items:

```js
braces('{foo,bar}')
//=> ['(foo|bar)']
picomatch.parse('{foo,bar}').output
//=> '(foo|bar)'
```

It seems to me like the behavior should match in both cases.

**Comment by mojavelinux** [comment]
I also find this comment from the README confusing:

> Picomatch does not do brace expansion.

Based on what I'm seeing, picomatch appears to support all sorts of brace expansion.

**Comment by jonschlinkert** [comment]
> Picomatch does not do brace expansion.

Brace _**expansion**_ is not the same as brace _**matching**_.

Expansion does this: `{a,b,c}` => `['a', 'b', 'c']`. 

> braces expansion should not match a single item like `{foo}`.

Agreed, this is a bug. Thanks for creating the issue.

**Comment by mojavelinux** [comment]
> Brace expansion is not the same as brace matching.

Aha! That makes sense. Thanks for clarifying.
