### ISSUE TITLE
Possibly missed `logical not` operator

### ISSUE THREAD

**Issue by mbelsky** [micromatch/picomatch#56]
Hey,

I may have missed something or wrongly understanded what the `posix` variable mean, but it looks like a logical not operator missed there:

https://github.com/micromatch/picomatch/blob/master/lib/picomatch.js#L48

**Comment by jonschlinkert** [comment]
> I may have missed something or wrongly understanded what the `posix` variable mean, but it looks like a logical not operator missed there:

The `posix` variable should tell us if the path needs to be converted to posix (forward) slashes. It's entirely possible that I made a mistake though.

**Comment by jonschlinkert** [comment]
Closing for now, since I think my link above should answer your question. Please feel free to reopen if there is a specific bug or issue you're having with this.
