### ISSUE TITLE
Windows and Linux generate different regexes

### ISSUE THREAD

**Issue by arcanis** [micromatch/picomatch#60]
The following command lines will yield different results:

```
$ yarn node -p "require('path').sep = '\\\\'; require('micromatch').makeRe('/')"
/^(?:[\\\/])$/
```

```
$ yarn node -p "require('path').sep = '/'; require('micromatch').makeRe('/')"
/^(?:\/)$/
```

This is problematic for how we use it in Yarn, because we need to generate a regex portable across systems.

**Comment by arcanis** [comment]
Of note, it seems to work if I pass the `windows: false` option. I'm not sure whether it's public however, since I only found it with a bit of luck in my searches 🤔

**Comment by jonschlinkert** [comment]
> This is problematic for how we use it in Yarn, because we need to generate a regex portable across systems.

Can you link to the issue you received so we can help debug? 

Also, it would help for you to explain what the correct behavior for slashes should be when:

1. The user overrides `path.sep` with double backslashes on a non-Windows OS
1. The user overrides `path.sep` with a single forward slash on a Windows OS
1. `path.sep` is two double backslashes on Windows
1. `path.sep` is a single forward slash on non-Windows

**Comment by arcanis** [comment]
Someone recently made a PR on Windows which baked a Windows-aware regex into a checked-in file. Then when I made a PR of my own on OSX it changed the line again:

https://github.com/yarnpkg/berry/pull/667/files#diff-25f1dd619d278877ef27d39e0990b85dL183

In general we might be a special case - we have our own translation layer for non-Posix paths, so we just always want to only support Posix paths. The only thing that matters in our case is that all systems generate the exact same regex.

**Comment by jonschlinkert** [comment]
> so we just always want to only support Posix paths

Got it, this helps. 

> Of note, it seems to work if I pass the `windows: false` option.

Yes, this is most likely the best solution for your use case, I think it should accomplish what you need in regards to ensuring posix slashes. 

> I'm not sure whether it's public however, since I only found it with a bit of luck in my searches

Thanks for mentioning that, it wasn't intentionally kept buried.

**Comment by jonschlinkert** [comment]
@arcanis I'm going to close since we have another issue open to add the `windows` option to docs, but please feel free to reopen or create a new issue if this is still causing problems for you.
