### ISSUE TITLE
`path` and `process` dependencies

### ISSUE THREAD

**Issue by silverwind** [micromatch/picomatch#64]
I'd like to run this module in a browser. Would it be resonable to ask these dependencies to be made optional?

**Comment by silverwind** [comment]
It appears this module works in browsers via the magic of webpack's node shims. But there are a few minor issues:

1. `process.version` used [here](https://github.com/micromatch/picomatch/blob/66e1b200f3ea1784bdeae0770c8e5cd95f55e334/lib/utils.js#L24-L30) is `''` in webpack so this check will never be successful.

2. Only `basename` and `sep` is used from `path`. I suggest doing `const {basename, sep} = require('path')` instead of importing the whole module to enable tree shaking.

**Comment by jasonwilliams** [comment]
@silverwind using node shims is no longer the recommended direction from Webpack v5 onwards.
Instead, this package should generate 2 bundles:
- A "node" version which is just a bundled version of what's there already.
- A "browser/web" version which doesn't try to use `processs` and `path`.
Once that's done you can add`"browser": "./path/to/browser-version.js"` to the package.json instead.

As for process i think you can just check if `process` exists in the code before using it, then fall back to something reasonable.
With `path` you can have some polyfill object in the webpack config which is used as a fallback. sep [can always return /](https://stackoverflow.com/questions/125813/how-to-determine-the-os-path-separator-in-javascript) and [basename](https://stackoverflow.com/questions/3820381/need-a-basename-function-in-javascript) can be added too.

This should be a relatively easy PR for anyone to do.

**Comment by silverwind** [comment]
I think the best course of action would be to extract just the matcher (basically `.isMatch`) to its own package. The matcher itself will never have dependency on the file system so should be universally portable.

**Comment by jasonwilliams** [comment]
@silverwind is this a change you're planning to PR?

**Comment by silverwind** [comment]
Not planning on a PR, maybe a fork/rewrite would be more appropriate. I think with `sep` made an option (or dropped entirely because nobody cares about Windows), the module's bundle size could be reduced by a lot. Just looking at the API, it seems to have a few redundant methods that are ripe to remove.

**Comment by jasonwilliams** [comment]
Ok in that case i think https://github.com/micromatch/picomatch/issues/64#issuecomment-732228132 is still worth doing, as a rewrite is a quite a big change and maybe out of scope for the issue we have here.

also TIL about bundlephobia

**Comment by jasonwilliams** [comment]
What do @mrmlnc or @jonschlinkert think about this?

**Comment by silverwind** [comment]
So I took a look at removing those dependencies, `path.basename` is easily replaced by a regex replacement but `process` is being used to alter the module's behaviour when running on Windows (on Windows, this module seems accept both forward and backward slashes as path separators, on other platforms only forward slashes).

So to cleanly remove `process`, I think a `windows` option needs to be added and has to be passed in by the user like `process.platform == "win32"` which of course is a breaking change.

**Comment by silverwind** [comment]
https://github.com/micromatch/picomatch/pull/73
