### ISSUE TITLE
Incorrect matching with curly braces and globstar

### ISSUE THREAD

**Issue by mrmlnc** [micromatch/picomatch#8]
#### Source

* mrmlnc/fast-glob#159

#### Actual behavior

The following filepathes is not matched by `minimatch`, `micromatch` and `picomatch` for the `{file.txt,directory/**/*}` pattern.

```
directory/.test.txt
directory/test.txt
```

But if you remove the `/*` part of the pattern, everything works correctly.

#### Expected behavior

Will be matched or documented :)

#### Code sample

Works fine:

```js
picomatch.makeRe('{file.txt,directory/**}', { dot: true });
```

* https://runkit.com/mrmlnc/5c6db74af4685d0012b8a037

Works bad:

```js
picomatch.makeRe('{file.txt,directory/**/*}', { dot: true });
```

* https://runkit.com/mrmlnc/5c6db7a2629c26001267cf8d

**Comment by jonschlinkert** [comment]
Thanks for the issue. Good timing too, since I'm working on this again this week.
